[[characters]]
class = 0
initiative = 4
name = 'Mico de Lorraine'
uuid = '5db8e3b0-6a9a-4d74-849d-885efbc77bcf'

[[characters]]
class = 0
initiative = 4
name = 'Regnar'
uuid = '32d5550d-ae7a-4987-a565-fb2eca89b2f4'